apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vendfinder
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format json_analytics escape=json
        '{'
            '"timestamp": "$time_iso8601",'
            '"remote_addr": "$remote_addr",'
            '"request": "$request",'
            '"status": "$status",'
            '"body_bytes_sent": "$body_bytes_sent",'
            '"http_referer": "$http_referer",'
            '"http_user_agent": "$http_user_agent",'
            '"request_time": "$request_time",'
            '"upstream_response_time": "$upstream_response_time"'
        '}';

        access_log /var/log/nginx/access.log json_analytics;
        error_log /var/log/nginx/error.log;

        sendfile        on;
        keepalive_timeout  65;
        
        # Enable gzip compression
        gzip on;
        gzip_types text/css application/javascript text/javascript application/json;
        
        server {
            listen       80;
            server_name  localhost;
            
            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
                try_files $uri $uri/ /index.html;
                
                # Cache static assets
                location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico)$ {
                    expires 1M;
                    add_header Cache-Control "public, immutable";
                }
            }
            
            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }
